version: '3'

volumes:
  my_blog:
  test_my_blog:

services:
  app:
    container_name: my_blog_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my-blog-network
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    depends_on:
      - blog_db

  blog_db:
    container_name: my_blog_db_container
    image: postgres:15.3-bullseye
    ports:
      - "5435:5432"
    networks:
      - my-blog-network
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes:
      - my_blog:/var/lib/postgresql/data

  test_db:
    container_name: test_blog_db
    image: postgres:15.3-bullseye
    ports:
      - "5436:5432"
    networks:
      - my-blog-network
    env_file:
      - .env.test
    environment:
      - DB_PROTOCOL="postgresql+asyncpg"
      - POSTGRES_USER=test_me
      - POSTGRES_PASSWORD=testpass123
      - DB_HOST=127.0.0.1
      - DB_PORT=5436
      - POSTGRES_DB=test_my_blog_db
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    volumes:
      - test_my_blog:/var/lib/postgresql/data

networks:
  my-blog-network:
    driver: bridge

