version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - some-name
    volumes:
      - my_blog:/opt/src
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    depends_on:
      - Blog_db

  Blog_db:
    container_name: bewisetask1_db_2
    image: postgres:15.3-bullseye
    ports:
      - "5435:5432"
    networks:
      - blog-network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  blog-network:
    driver: bridge

volumes:
  my_blog: