version: '3'

volumes:
  my_blog:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my-blog-network
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .db_env
    depends_on:
      - blog_db

  blog_db:
    container_name: my_blog_db
    image: postgres:15.3-bullseye
    ports:
      - "5435:5432"
    networks:
      - my-blog-network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes:
      - my_blog:/var/lib/postgresql/data

networks:
  my-blog-network:
    driver: bridge

