"""_init_migration

Revision ID: 228bb4ab8797
Revises: 
Create Date: 2023-08-14 15:30:53.693466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228bb4ab8797'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('user_login', sa.String(length=20), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_uuid'),
    sa.UniqueConstraint('user_login')
    )
    op.create_index(op.f('ix_users_table_user_uuid'), 'users_table', ['user_uuid'], unique=False)
    op.create_table('users_posts',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('post_header', sa.String(length=50), nullable=False),
    sa.Column('post_text', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.user_uuid'], ),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('post_header')
    )
    op.create_index(op.f('ix_users_posts_post_id'), 'users_posts', ['post_id'], unique=False)
    op.create_table('dislikes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['users_posts.post_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['users_posts.post_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('dislikes')
    op.drop_index(op.f('ix_users_posts_post_id'), table_name='users_posts')
    op.drop_table('users_posts')
    op.drop_index(op.f('ix_users_table_user_uuid'), table_name='users_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
