"""some fixes

Revision ID: 234824db25f0
Revises: b27104fe30ac
Create Date: 2023-10-25 20:53:57.086548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234824db25f0'
down_revision = 'b27104fe30ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
