"""added email column to Users

Revision ID: 3d501637eee4
Revises: 228bb4ab8797
Create Date: 2023-09-02 11:41:49.464206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d501637eee4'
down_revision = '228bb4ab8797'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('email', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'users_table', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_table', type_='unique')
    op.drop_column('users_table', 'email')
    # ### end Alembic commands ###
