"""fixed error in back_population for posts and likes

Revision ID: 3e6bf2471bda
Revises: dc7ec52a28d7
Create Date: 2023-09-25 00:27:29.330641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6bf2471bda'
down_revision = 'dc7ec52a28d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
