"""added cascades to models

Revision ID: 57fa03b352df
Revises: 5cd91b62a771
Create Date: 2023-10-26 10:18:15.332423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57fa03b352df'
down_revision = '5cd91b62a771'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
