"""removed userreactions table

Revision ID: 842e8d1db538
Revises: a6a87015cc75
Create Date: 2023-10-26 13:55:45.479537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842e8d1db538'
down_revision = 'a6a87015cc75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_reactions')
    op.create_unique_constraint(None, 'dislikes', ['post_id', 'placed_by'])
    op.create_unique_constraint(None, 'likes', ['post_id', 'placed_by'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='unique')
    op.drop_constraint(None, 'dislikes', type_='unique')
    op.create_table('users_reactions',
    sa.Column('rec_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.user_uuid'], name='users_reactions_user_id_fkey'),
    sa.PrimaryKeyConstraint('rec_id', name='users_reactions_pkey')
    )
    # ### end Alembic commands ###
