"""edited cascades

Revision ID: a6a87015cc75
Revises: 57fa03b352df
Create Date: 2023-10-26 12:25:13.038999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a87015cc75'
down_revision = '57fa03b352df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
