"""added creation dates for likes and dislikes

Revision ID: b27104fe30ac
Revises: 3e6bf2471bda
Create Date: 2023-09-25 00:44:04.297614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27104fe30ac'
down_revision = '3e6bf2471bda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dislikes', sa.Column('is_valid', sa.Boolean(), nullable=False))
    op.add_column('dislikes', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('dislikes', sa.Column('date_updated', sa.DateTime(), nullable=False))
    op.add_column('likes', sa.Column('is_valid', sa.Boolean(), nullable=False))
    op.add_column('likes', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('likes', sa.Column('date_updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'date_updated')
    op.drop_column('likes', 'date_created')
    op.drop_column('likes', 'is_valid')
    op.drop_column('dislikes', 'date_updated')
    op.drop_column('dislikes', 'date_created')
    op.drop_column('dislikes', 'is_valid')
    # ### end Alembic commands ###
