"""added backpopulation

Revision ID: dc7ec52a28d7
Revises: 3d501637eee4
Create Date: 2023-09-25 00:13:10.383947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7ec52a28d7'
down_revision = '3d501637eee4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
